### ISSUE TITLE
Frontend Development

### ISSUE THREAD

**Issue by MesfinGithinji** [ecitizen-ke/ecitizen-fb-chatbot#4]
1. Design UI/UX for admin dashboard.
2. Implement frontend components for viewing messages and analytics.
3. Integrate frontend with backend API.

**Comment by MesfinGithinji** [comment]
Attention all team members . Lets use this branch for our front end development

**Comment by maxwelbarno** [comment]
- [x] Upgrade from `create react app` to `vite`
- [x] Provision `vite` spin-up configurations
- [x] Refactor project directories
- [x] Upgrade necessary files to `JSX` grade
- [x] Create custom utility hooks
- [x] create and group context files
- [x] Update footer text
- [x] Update page title
- [x]  Uninstall `axios` and use out-of-the-box `fetch` function
